### ISSUE TITLE
More then Two inputs

### ISSUE THREAD

**Issue by matthewryanburgin191** [dmadison/CtrlUtil#1]
Hi,

I just tested the dz sketch but I couldn't create more then two instances.

const float ZoneSizeX = 0.15;  // 15 %
const auto  ZonePositionX = DeadzoneFilter::Middle;
DeadzoneFilter dzX(ZoneSizeX, ZonePositionX);

const float ZoneSizeY = 0.25;  // 25 %
const auto  ZonePositionY = DeadzoneFilter::Middle;
DeadzoneFilter dzY(ZoneSizeY, ZonePositionY);

Only dzX works.

best regards.

Matthew

**Comment by dmadison** [comment]
Hi Matthew. Could you clarify for me, what isn't working? Does the code compile? Is the class returning bad data?

**Comment by matthewryanburgin191** [comment]
sorry dzx works and outputs perfectly dzy will just output raw data.
compiles fine.

I'm guessing ive missed something obvious!
cheers

**Comment by dmadison** [comment]
Do you have a full example to test? I just tried using that snippet with the example program and had no issues.

Also, what is your hardware setup (board and wiring), and what version of the Arduino IDE are you using?

**Comment by matthewryanburgin191** [comment]
I'm using a Mega2560 board running ros-serial IDE 1.815

const float ZoneSizeX = 0.15;  // 15 %
const auto  ZonePositionX = DeadzoneFilter::Middle;
DeadzoneFilter dzX(ZoneSizeX, ZonePositionX);

const float ZoneSizeY = 0.15;  // 15 %
const auto  ZonePositionY = DeadzoneFilter::Middle;
DeadzoneFilter dzY(ZoneSizeY, ZonePositionY);

void sendmessage(){


    int XrawValue = analogRead(A1);
    int XdzValue = dzX.filter(XrawValue);
    joystick[1] = map(XdzValue, 0, 1023, 0, 255);

    int YrawValue = analogRead(A0);
    int YdzValue = dzY.filter(YrawValue);
    joystick[2] = map(YrawValue, 0, 1023, 0, 255);
    
    joystick[3] = map(analogRead(A2), 0, 300, 0, 255);

    
    if (_radio.send(DESTINATION_RADIO_ID, &joystick, sizeof(joystick)))
    {
     //   Serial.println("...Success");
    }
    else
    {
        //Serial.println("...Failed");
    }
 
}

**Comment by dmadison** [comment]
```cpp
int YrawValue = analogRead(A0);
int YdzValue = dzY.filter(YrawValue);
joystick[2] = map(YrawValue, 0, 1023, 0, 255);
```
You're filtering the raw value and then saving the raw value instead of the filtered value. That last line should use `YdzValue` instead of `YrawValue`.

**Comment by matthewryanburgin191** [comment]
haha, thank you for your time! I will eventually learn to read one day.

**Comment by dmadison** [comment]
Happens to the best of us. Good luck on the project!
